-- Seed data for Elite Sports Management
-- Run AFTER supabase-schema.sql

insert into players (slug, name, "group", position, country, flag, heritage, born, birthplace, tier, bats, bio, teams, stats, sort_order) values
  ('brayan-hernandez', 'Brayan Hernández', 'Two-Way', 'Two-Way (C / 1B / OF)', 'Dominican Republic', '🇩🇴', null, '2001', 'La Vega, Dominican Republic', 'Pro', 'Left', 'A versatile two-way player out of La Vega known for his offensive power from the left side. Developed in the Baltimore Orioles organization, he can catch, play first base and patrol the outfield.', '["Baltimore Orioles org.", "Delmarva Shorebirds", "Aberdeen IronBirds"]'::jsonb, '[]'::jsonb, 0),
  ('gianni-westphal', 'Gianni Westphal', 'Pitcher', 'Pitcher (RHP)', 'Venezuela', '🇻🇪', '🇩🇪', '2001', 'Caracas, Venezuela', 'International', null, 'A Venezuelan pitcher with German citizenship known for a 90 mph fastball and a deep repertoire of slider, sinker and changeup. Played in the German Bundesliga before signing in Italy''s Serie B.', '["Dortmund Wanderers (GER)", "Livorno Baseball 1948 (ITA · Serie B)"]'::jsonb, '[{"label": "Fastball", "value": "90 mph"}]'::jsonb, 1),
  ('jose-cedeno', 'José Cedeño', 'Catcher', 'Catcher', 'Venezuela', '🇻🇪', null, null, 'Venezuela', 'Pro', null, 'A talented catcher developed in the Cleveland Guardians organization after signing as an international prospect. Recognized for his defense behind the plate and a mature approach at a young age.', '["Cleveland Guardians org.", "Dominican Summer League", "Arizona Complex League"]'::jsonb, '[]'::jsonb, 2),
  ('danyer-sanabria', 'Danyer Sanabria', 'Infielder', 'Infielder', 'Venezuela', '🇻🇪', null, null, 'Venezuela', 'Pro', null, 'A Venezuelan talent who has represented his country at the U23 level. Brings experience from affiliated ball plus winter leagues in Argentina and Venezuela and three seasons in Venezuela''s Liga Mayor.', '["Arizona Diamondbacks org.", "Venezuela U23", "Liga Mayor (VEN)"]'::jsonb, '[]'::jsonb, 3),
  ('francesco-mazzei', 'Francesco Mazzei', 'Two-Way', 'Two-Way', 'Spain', '🇪🇸', null, null, 'Madrid, Spain', 'International', null, 'A Spanish talent from Madrid who has represented Spain at both the U18 and U23 national-team levels. A standout in the Spanish baseball system pursuing the U.S. college route.', '["Spain National Team (U18 / U23)"]'::jsonb, '[]'::jsonb, 4),
  ('anderson-pena', 'Anderson Peña', 'Infielder', 'Infielder', 'Spain', '🇪🇸', null, '2006', 'Spain', 'International', null, 'A Spanish infielder developed at the Regensburg Baseball Academy, known for strong defense and contact hitting. Has represented Spain internationally and is pursuing U.S. college baseball with pro potential.', '["Spain National Team", "Regensburg Baseball Academy"]'::jsonb, '[]'::jsonb, 5),
  ('jesus-delgado', 'Jesús Delgado', 'Pitcher', 'Pitcher (LHP)', 'Venezuela', '🇻🇪', null, '2003', 'Guanare, Venezuela', 'Pro', null, 'A left-handed pitcher signed by the Texas Rangers in 2023 who has shown big projection in the minors. Shined as a 2024 DSL All-Star and continued his development in the Arizona Complex League.', '["Texas Rangers org.", "Arizona Complex League"]'::jsonb, '[{"label": "2024 DSL", "value": "All-Star"}, {"label": "Strikeouts", "value": "83 in 64 IP"}]'::jsonb, 6),
  ('lorenzo-gonzalez', 'Lorenzo González', 'Catcher', 'Catcher', 'Venezuela', '🇻🇪', null, null, 'Venezuela', 'College', null, 'A catcher at Campbellsville University whose game is built on consistent receiving, strong blocking and a quick release. Brings leadership and reliable game-calling behind the plate.', '["Campbellsville University (NAIA)"]'::jsonb, '[]'::jsonb, 7),
  ('jaider-morelos', 'Jaider Morelos', 'Infielder', 'Infielder', 'Colombia', '🇨🇴', null, null, 'Colombia', 'College', null, 'A Colombian collegiate player competing at the NAIA level with Montreat College. Known for defensive consistency, versatility and a strong work ethic against high-level college talent.', '["Montreat College (NAIA)"]'::jsonb, '[]'::jsonb, 8),
  ('bret-bowers', 'Bret Bowers', 'Infielder', 'Infielder', 'United States', '🇺🇸', null, null, 'United States', 'College', null, 'A collegiate player developed within the Campbellsville University program at the NAIA level. A member of the Tigers known for his work ethic and coachability against high-level competition.', '["Campbellsville University (NAIA)"]'::jsonb, '[]'::jsonb, 9),
  ('osiris-german', 'Osiris Germán', 'Pitcher', 'Pitcher (RHP)', 'Dominican Republic', '🇩🇴', null, null, 'Dominican Republic', 'Pro', null, 'A professional Dominican pitcher developed in the Minnesota Twins organization after signing as an international free agent in 2016. Advanced to Double-A and earned MLB Spring Training invites with the Twins.', '["Minnesota Twins org.", "Wichita Wind Surge (AA)", "MLB Spring Training"]'::jsonb, '[]'::jsonb, 10),
  ('adam-moser', 'Adam Moser', 'Infielder', 'Infielder / Utility', 'United States', '🇺🇸', null, null, 'Arizona, USA', 'College', 'Right', 'An Arizona native and former Sunrise Mountain High School standout who went on to play infield at College of the Desert. A versatile utility player with elite hitting and an exciting power-and-defense profile.', '["Sunrise Mountain HS", "College of the Desert"]'::jsonb, '[{"label": "2024 AVG", "value": ".317"}, {"label": "Home Runs", "value": "6"}, {"label": "SLG", "value": ".545"}]'::jsonb, 11),
  ('yerardo-ciofani', 'Yerardo Ciofani', 'Pitcher', 'Pitcher (LHP)', 'Venezuela', '🇻🇪', null, '2006', 'Maracaibo, Venezuela', 'Pro', null, 'A left-handed pitcher born in Maracaibo who signed with the Chicago White Sox in December 2023. Played for the DSL White Sox in 2024, posting a strong rookie campaign.', '["Chicago White Sox org.", "DSL White Sox"]'::jsonb, '[{"label": "2024 Record", "value": "5-1"}, {"label": "Strikeouts", "value": "25"}, {"label": "WHIP", "value": "2.16"}]'::jsonb, 12),
  ('javier-useche', 'José Javier Useche', 'Pitcher', 'Pitcher (RHP)', 'Venezuela', '🇻🇪', '🇵🇹', null, 'Venezuela', 'International', null, 'A young Venezuelan-Portuguese right-hander who has stood out in Italy''s Serie B with Porto Sant''Elpidio. Recognized for discipline, precision and competitive maturity, combining power with control.', '["Porto Sant''Elpidio (ITA · Serie B)"]'::jsonb, '[]'::jsonb, 13),
  ('david-chavez', 'David Chávez', 'Pitcher', 'Pitcher (RHP)', 'Venezuela', '🇻🇪', null, null, 'Venezuela', 'International', null, 'A young right-handed pitcher active on the roster of a Serie A team in Italy. His place at a higher level positions him as a player with real growth potential on the Italian league''s visibility window.', '["Serie A (Italy)"]'::jsonb, '[]'::jsonb, 14),
  ('matteo-colalucci', 'Matteo Colalucci', 'Two-Way', 'Pitcher / Infielder', 'Italy', '🇮🇹', null, '2004', 'Anzio, Italy', 'International', 'Right', 'An Italian pitcher and infielder who has played in Serie A and helped earn promotion to Serie B in 2025. Won a silver medal with Italy''s U15 national team at the European Championship.', '["Serie A / Serie B (Italy)", "Italy U15 National Team"]'::jsonb, '[{"label": "U15 Euros", "value": "🥈 Silver"}]'::jsonb, 15),
  ('anthony-quattrocchi', 'Anthony Quattrocchi', 'Pitcher', 'Pitcher (RHP)', 'United States', '🇺🇸', null, null, 'Surprise, Arizona, USA', 'Pro', null, 'A right-handed pitcher recognized for velocity and precision. Set the school strikeout record at Ottawa University Arizona and earned NCCAA First Team All-American honors before advancing to the pro independent leagues.', '["Ottawa University AZ", "Lake Erie (Frontier)", "Staten Island FerryHawks (Atlantic)", "Idaho Falls Chukars (Pioneer)"]'::jsonb, '[{"label": "College", "value": "7-2, 2.55 ERA"}, {"label": "Strikeouts", "value": "83 (school record)"}, {"label": "2021", "value": "NCCAA 1st Team A-A"}]'::jsonb, 16)
on conflict (slug) do nothing;
